### ISSUE TITLE
infer() does not handle unicode strings

### ISSUE THREAD

**Issue by nchammas** [bruth/strconv#2]
Unicode strings seem to mess with infer()'s mojo:

```
>>> strconv.infer('2004-05-06')
'datetime'
>>> strconv.infer(u'2004-05-06')
>>> 
```

Here is a simple work-around (picked up from [here](http://stackoverflow.com/a/1211102/)):

```
>>> strconv.infer(u'2004-05-06'.encode('ascii', 'ignore'))
'datetime'
```

This work-around appears to be safe for most types of input except non-English datetime strings (e.g. [março](http://www.brazil-help.com/months.htm)), and strconv doesn't appear to handle non-English months anyway.

```
>>> strconv.infer('January 26, 2014')
'datetime'
>>> strconv.infer('janvier 26, 2014')
>>> 
```

**Comment by bruth** [comment]
@nchammas Thanks for the report and sorry for the late response. I would welcome contributions to internalize the library.

**Comment by chid** [comment]
You could use the dateparser library rather than dateutil.

```
In [1]: import dateparser

In [2]: dateparser.parse('January 26, 2014')
Out[2]: datetime.datetime(2014, 1, 26, 0, 0)

In [3]: dateparser.parse('janvier  26, 2014')
Out[3]: datetime.datetime(2014, 1, 26, 0, 0)
```
